function [transition_matrix, emission_matrix] = estimate_hmm_transition_matrix( ...
    observed_sequence, initial_transition_matrix, initial_emission_matrix, hmmtrain_settings)
%ESTIMATE_HMM_TRANSITION_MATRIX Small wrapper around hmmtrain for Problem 2.5.

observed_sequence = observed_sequence(:).';

[transition_matrix, emission_matrix] = hmmtrain( ...
    observed_sequence, ...
    initial_transition_matrix, ...
    initial_emission_matrix, ...
    'Algorithm', hmmtrain_settings.Algorithm, ...
    'Maxiterations', hmmtrain_settings.Maxiterations, ...
    'Tolerance', hmmtrain_settings.Tolerance);

end
