function main_problem_2_6()
%MAIN_PROBLEM_2_6 Run Module 12 Problem 2.6 limiting-distribution workflow.

script_dir = fileparts(mfilename('fullpath'));
repo_root = fileparts(script_dir);
utilities_dir = fullfile(repo_root, 'utilities');
problem_2_4_results_path = fullfile(repo_root, 'Problem_2_4_EnergyDetection', 'problem_2_4_results.mat');
problem_2_5_results_path = fullfile(repo_root, 'Problem_2_5_HMM', 'problem_2_5_results.mat');
results_path = fullfile(script_dir, 'problem_2_6_results.mat');

addpath(utilities_dir);

problem_2_4_data = load(problem_2_4_results_path, 'results');
problem_2_5_data = load(problem_2_5_results_path, 'results');

problem_2_4_results = problem_2_4_data.results;
problem_2_5_results = problem_2_5_data.results;

example_transition_matrix = problem_2_5_results.example_channel.transition_matrix;
example_limiting_distribution = compute_limiting_distribution(example_transition_matrix);

% Convert the steady-state probabilities into percentages so they can be
% compared directly to the measured occupancy numbers from Problem 2.4.
example_predicted_percent_idle = 100 * example_limiting_distribution(1);
example_predicted_percent_occupied = 100 * example_limiting_distribution(2);

example_observed_percent_idle = problem_2_4_results.example_channel.percent_idle;
example_observed_percent_occupied = problem_2_4_results.example_channel.percent_occupied;

% The example truth sequence uses two labels, so map the smaller one to
% idle and the larger one to occupied before taking percentages.
example_truth_sequence = problem_2_4_results.example_channel.truth_sequence(:);
example_truth_idle = example_truth_sequence == min(example_truth_sequence);
example_truth_occupied = example_truth_sequence == max(example_truth_sequence);
example_truth_percent_idle = 100 * mean(example_truth_idle);
example_truth_percent_occupied = 100 * mean(example_truth_occupied);

example_predicted_minus_observed_idle_percent = ...
    example_predicted_percent_idle - example_observed_percent_idle;
example_predicted_minus_observed_occupied_percent = ...
    example_predicted_percent_occupied - example_observed_percent_occupied;
example_predicted_minus_truth_idle_percent = ...
    example_predicted_percent_idle - example_truth_percent_idle;
example_predicted_minus_truth_occupied_percent = ...
    example_predicted_percent_occupied - example_truth_percent_occupied;

num_channels = numel(problem_2_5_results.channels);
channel_results = repmat(struct( ...
    'transition_matrix', [], ...
    'limiting_distribution', [], ...
    'predicted_percent_idle', [], ...
    'predicted_percent_occupied', [], ...
    'observed_percent_idle', [], ...
    'observed_percent_occupied', []), num_channels, 1);

predicted_occupied_percentages = zeros(num_channels, 1);

for channel_idx = 1:num_channels
    transition_matrix = problem_2_5_results.channels(channel_idx).transition_matrix;
    limiting_distribution = compute_limiting_distribution(transition_matrix);

    predicted_percent_idle = 100 * limiting_distribution(1);
    predicted_percent_occupied = 100 * limiting_distribution(2);

    channel_results(channel_idx).transition_matrix = transition_matrix;
    channel_results(channel_idx).limiting_distribution = limiting_distribution;
    channel_results(channel_idx).predicted_percent_idle = predicted_percent_idle;
    channel_results(channel_idx).predicted_percent_occupied = predicted_percent_occupied;
    channel_results(channel_idx).observed_percent_idle = ...
        problem_2_4_results.channels(channel_idx).percent_idle;
    channel_results(channel_idx).observed_percent_occupied = ...
        problem_2_4_results.channels(channel_idx).percent_occupied;

    predicted_occupied_percentages(channel_idx) = predicted_percent_occupied;
end

% The quietest channels are the ones with the lowest long-term occupied
% probability, since those should be best for secondary access.
[sorted_predicted_occupied, sort_idx] = sort(predicted_occupied_percentages, 'ascend');
quietest_channel_indices = sort_idx(1:2);
quietest_channel_predicted_occupied_percentages = sorted_predicted_occupied(1:2);

results = struct();
results.example_channel = struct( ...
    'transition_matrix', example_transition_matrix, ...
    'limiting_distribution', example_limiting_distribution, ...
    'predicted_percent_idle', example_predicted_percent_idle, ...
    'predicted_percent_occupied', example_predicted_percent_occupied, ...
    'observed_percent_idle', example_observed_percent_idle, ...
    'observed_percent_occupied', example_observed_percent_occupied, ...
    'truth_percent_idle', example_truth_percent_idle, ...
    'truth_percent_occupied', example_truth_percent_occupied, ...
    'predicted_minus_observed_idle_percent', example_predicted_minus_observed_idle_percent, ...
    'predicted_minus_observed_occupied_percent', example_predicted_minus_observed_occupied_percent, ...
    'predicted_minus_truth_idle_percent', example_predicted_minus_truth_idle_percent, ...
    'predicted_minus_truth_occupied_percent', example_predicted_minus_truth_occupied_percent);
results.channels = channel_results;
results.summary = struct( ...
    'quietest_channel_indices', quietest_channel_indices, ...
    'quietest_channel_predicted_occupied_percentages', quietest_channel_predicted_occupied_percentages);
results.metadata = struct( ...
    'state_definition', 'S1_idle_S2_occupied', ...
    'transition_matrix_orientation', 'rows_current_state_columns_next_state', ...
    'limiting_distribution_method', 'two_state_closed_form');

save(results_path, 'results');

fprintf('Problem 2.6 results saved to %s\n', results_path);
fprintf('Example predicted idle: %.4f%%, occupied: %.4f%%\n', ...
    results.example_channel.predicted_percent_idle, ...
    results.example_channel.predicted_percent_occupied);
fprintf('Example observed idle: %.4f%%, occupied: %.4f%%\n', ...
    results.example_channel.observed_percent_idle, ...
    results.example_channel.observed_percent_occupied);
fprintf('Example truth idle: %.4f%%, occupied: %.4f%%\n', ...
    results.example_channel.truth_percent_idle, ...
    results.example_channel.truth_percent_occupied);

for channel_idx = 1:num_channels
    fprintf('Channel %d predicted idle: %.4f%%, occupied: %.4f%%\n', ...
        channel_idx, ...
        results.channels(channel_idx).predicted_percent_idle, ...
        results.channels(channel_idx).predicted_percent_occupied);
end

fprintf('Quietest channels: %d and %d\n', ...
    results.summary.quietest_channel_indices(1), ...
    results.summary.quietest_channel_indices(2));

end
